spring:
  security:
    user:
      name: root
      password: P@ssw0rd

logging:
  level:
    root: info
    org:
      hibernate:
        type: info
        SQL: debug
    com:
      carmel:
        olive: trace

  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'

  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 5MB
